// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2S02DmlzwNOTMhIaqQg-zlmZ1p4Lu7BU',
    appId: '1:801367357743:web:8602db5cdf9173b26ec9da',
    messagingSenderId: '801367357743',
    projectId: 'chat-app-7108b',
    authDomain: 'chat-app-7108b.firebaseapp.com',
    storageBucket: 'chat-app-7108b.appspot.com',
    measurementId: 'G-LVFYJZEC5F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMdNNWPhtI3xL_yN0SfS7kG02lmLnYR6A',
    appId: '1:801367357743:android:cbbb40695681110c6ec9da',
    messagingSenderId: '801367357743',
    projectId: 'chat-app-7108b',
    storageBucket: 'chat-app-7108b.appspot.com',
  );
}
